/**
 * The class 'Altavoz' contains the sound generated by the relog and its melody
 */
package miniproyecto;

/**
 * The constructor defines the variable 'melodia' as type String
 * @author Miguel Sánchez Blanco
 */
public class Altavoz {
    
    static String melodia;
    static boolean ringON;
    /**
    * The 'playSound' method is responsible for reproducing the sound
    */
    public static void playSound(){
        System.out.println("tu Musica");
    }
    
    /**
     * The 'ringON' method indicates the sound state
     */
    public static void ringON(){
        System.out.println("Alarma Apagada");
    }
    
    
}
